//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFitness.View.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyFitness.View.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity was not found.
        /// </summary>
        internal static string ActivityNotFound {
            get {
                return ResourceManager.GetString("ActivityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity successfully deleted.
        /// </summary>
        internal static string ActivitySucDel {
            get {
                return ResourceManager.GetString("ActivitySucDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to add another meal?.
        /// </summary>
        internal static string AddAnotherMeal_ {
            get {
                return ResourceManager.GetString("AddAnotherMeal?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E - Add exercise.
        /// </summary>
        internal static string AddExercise {
            get {
                return ResourceManager.GetString("AddExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F - Add food intake.
        /// </summary>
        internal static string AddFoodIntake {
            get {
                return ResourceManager.GetString("AddFoodIntake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to enter additional information for a meal?.
        /// </summary>
        internal static string AddInform_ {
            get {
                return ResourceManager.GetString("AddInform?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A - List of all existing activities.
        /// </summary>
        internal static string AllActivities {
            get {
                return ResourceManager.GetString("AllActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M - List of all existing meals.
        /// </summary>
        internal static string AllMeals {
            get {
                return ResourceManager.GetString("AllMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of kilocalories burned: .
        /// </summary>
        internal static string AmountBurnedKcal {
            get {
                return ResourceManager.GetString("AmountBurnedKcal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit the application.
        /// </summary>
        internal static string AppExit {
            get {
                return ResourceManager.GetString("AppExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyFitness was started!.
        /// </summary>
        internal static string AppStarted {
            get {
                return ResourceManager.GetString("AppStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbohydrates: .
        /// </summary>
        internal static string Carbs {
            get {
                return ResourceManager.GetString("Carbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        internal static string cm {
            get {
                return ResourceManager.GetString("cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Y to confirm or N to refuse.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carbohydrates.
        /// </summary>
        internal static string crbs {
            get {
                return ResourceManager.GetString("crbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user: .
        /// </summary>
        internal static string CurrentUser {
            get {
                return ResourceManager.GetString("CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date of birth.
        /// </summary>
        internal static string dateOfBirth {
            get {
                return ResourceManager.GetString("dateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the activity you want to delete: .
        /// </summary>
        internal static string Del_EnterActivityName {
            get {
                return ResourceManager.GetString("Del_EnterActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the time or date and start time of the exercise you want to delete: .
        /// </summary>
        internal static string Del_EnterExerciseStartTime {
            get {
                return ResourceManager.GetString("Del_EnterExerciseStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the moment (date and time) of the food intake you want to delete: .
        /// </summary>
        internal static string Del_EnterFoodIntakeMoment {
            get {
                return ResourceManager.GetString("Del_EnterFoodIntakeMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the meal you want to delete: .
        /// </summary>
        internal static string Del_EnterMealName {
            get {
                return ResourceManager.GetString("Del_EnterMealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete your account?.
        /// </summary>
        internal static string DeleteAccount_ {
            get {
                return ResourceManager.GetString("DeleteAccount?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration: .
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end time of the exercise.
        /// </summary>
        internal static string endExTime {
            get {
                return ResourceManager.GetString("endExTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of activity: .
        /// </summary>
        internal static string EnterActivityName {
            get {
                return ResourceManager.GetString("EnterActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the amount of carbohydrates .
        /// </summary>
        internal static string EnterCarbs {
            get {
                return ResourceManager.GetString("EnterCarbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter date of birth (min. 12 y.o.): .
        /// </summary>
        internal static string EnterDateOfBirth {
            get {
                return ResourceManager.GetString("EnterDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the end time of the exercise (format dd.MM.yyyy HH:mm or only HH.mm): .
        /// </summary>
        internal static string EnterExEndTime {
            get {
                return ResourceManager.GetString("EnterExEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the start time of the exercise (format dd.MM.yyyy HH:mm or only HH.mm): .
        /// </summary>
        internal static string EnterExStartTime {
            get {
                return ResourceManager.GetString("EnterExStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the amount of fats .
        /// </summary>
        internal static string EnterFats {
            get {
                return ResourceManager.GetString("EnterFats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter gender: .
        /// </summary>
        internal static string EnterGender {
            get {
                return ResourceManager.GetString("EnterGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter height (in centimeters): .
        /// </summary>
        internal static string EnterHeight {
            get {
                return ResourceManager.GetString("EnterHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the amount of kilocalories .
        /// </summary>
        internal static string EnterKcal {
            get {
                return ResourceManager.GetString("EnterKcal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of kilocalories burned per hour: .
        /// </summary>
        internal static string EnterKcalPerHour {
            get {
                return ResourceManager.GetString("EnterKcalPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter meal name: .
        /// </summary>
        internal static string EnterMealName {
            get {
                return ResourceManager.GetString("EnterMealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter meal weight: .
        /// </summary>
        internal static string EnterMealWeight {
            get {
                return ResourceManager.GetString("EnterMealWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product volume: .
        /// </summary>
        internal static string EnterProductVolume {
            get {
                return ResourceManager.GetString("EnterProductVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the amount of proteins  .
        /// </summary>
        internal static string EnterProteins {
            get {
                return ResourceManager.GetString("EnterProteins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username: .
        /// </summary>
        internal static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter weight (in kilograms): .
        /// </summary>
        internal static string EnterWeight {
            get {
                return ResourceManager.GetString("EnterWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise was not found.
        /// </summary>
        internal static string ExerciseNotFound {
            get {
                return ResourceManager.GetString("ExerciseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time or date and start time of the exercise.
        /// </summary>
        internal static string exerciseStartTime {
            get {
                return ResourceManager.GetString("exerciseStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise successfully deleted.
        /// </summary>
        internal static string ExerciseSucDel {
            get {
                return ResourceManager.GetString("ExerciseSucDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q - Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fats: .
        /// </summary>
        internal static string Fats {
            get {
                return ResourceManager.GetString("Fats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moment of the food intake.
        /// </summary>
        internal static string foodIntakeMoment {
            get {
                return ResourceManager.GetString("foodIntakeMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food intake was not found.
        /// </summary>
        internal static string FoodIntakeNotFound {
            get {
                return ResourceManager.GetString("FoodIntakeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food intake successfully deleted.
        /// </summary>
        internal static string FoodIntakeSucDel {
            get {
                return ResourceManager.GetString("FoodIntakeSucDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fats.
        /// </summary>
        internal static string fts {
            get {
                return ResourceManager.GetString("fts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        internal static string g {
            get {
                return ResourceManager.GetString("g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to height.
        /// </summary>
        internal static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect.
        /// </summary>
        internal static string Incorrect {
            get {
                return ResourceManager.GetString("Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the product a liquid?.
        /// </summary>
        internal static string IsLiquid_ {
            get {
                return ResourceManager.GetString("IsLiquid?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilocalories per hour.
        /// </summary>
        internal static string kcalPerHour {
            get {
                return ResourceManager.GetString("kcalPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilocalories.
        /// </summary>
        internal static string kcals {
            get {
                return ResourceManager.GetString("kcals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        internal static string kg {
            get {
                return ResourceManager.GetString("kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal was not found.
        /// </summary>
        internal static string MealNotFound {
            get {
                return ResourceManager.GetString("MealNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal successfully deleted.
        /// </summary>
        internal static string MealSucDel {
            get {
                return ResourceManager.GetString("MealSucDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meal weight.
        /// </summary>
        internal static string mealWeight {
            get {
                return ResourceManager.GetString("mealWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        internal static string ml {
            get {
                return ResourceManager.GetString("ml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per 100 g of the meal (just a number in grams): .
        /// </summary>
        internal static string Per100gMeal {
            get {
                return ResourceManager.GetString("Per100gMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per 100 ml of the product (just a number in grams): .
        /// </summary>
        internal static string Per100mlProduct {
            get {
                return ResourceManager.GetString("Per100mlProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, try again.
        /// </summary>
        internal static string PleaseTryAgain {
            get {
                return ResourceManager.GetString("PleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product volume.
        /// </summary>
        internal static string productVolume {
            get {
                return ResourceManager.GetString("productVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age: .
        /// </summary>
        internal static string Profile_Age {
            get {
                return ResourceManager.GetString("Profile_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI: .
        /// </summary>
        internal static string Profile_BMI {
            get {
                return ResourceManager.GetString("Profile_BMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth: .
        /// </summary>
        internal static string Profile_DateOfBirth {
            get {
                return ResourceManager.GetString("Profile_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender: .
        /// </summary>
        internal static string Profile_Gender {
            get {
                return ResourceManager.GetString("Profile_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height: .
        /// </summary>
        internal static string Profile_Height {
            get {
                return ResourceManager.GetString("Profile_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username: .
        /// </summary>
        internal static string Profile_Username {
            get {
                return ResourceManager.GetString("Profile_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile.
        /// </summary>
        internal static string Profile_UserProfile {
            get {
                return ResourceManager.GetString("Profile_UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight: .
        /// </summary>
        internal static string Profile_Weight {
            get {
                return ResourceManager.GetString("Profile_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proteins: .
        /// </summary>
        internal static string Proteins {
            get {
                return ResourceManager.GetString("Proteins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proteins.
        /// </summary>
        internal static string prts {
            get {
                return ResourceManager.GetString("prts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R - Return to the settings menu.
        /// </summary>
        internal static string R_ReturnSettingsMenu {
            get {
                return ResourceManager.GetString("R_ReturnSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to return to the main menu....
        /// </summary>
        internal static string ReturnMainMenu {
            get {
                return ResourceManager.GetString("ReturnMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to return to the settings menu....
        /// </summary>
        internal static string ReturnSettingsMenu {
            get {
                return ResourceManager.GetString("ReturnSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an action:.
        /// </summary>
        internal static string SelectAction {
            get {
                return ResourceManager.GetString("SelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the desired data service for the application.
        /// </summary>
        internal static string SelectDataService {
            get {
                return ResourceManager.GetString("SelectDataService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D - Database service.
        /// </summary>
        internal static string Service_Database {
            get {
                return ResourceManager.GetString("Service_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S - Serialization service.
        /// </summary>
        internal static string Service_Serialization {
            get {
                return ResourceManager.GetString("Service_Serialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application data service successfully changed to database service.
        /// </summary>
        internal static string ServiceSucChangedDb {
            get {
                return ResourceManager.GetString("ServiceSucChangedDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application data service successfully changed to serialization service.
        /// </summary>
        internal static string ServiceSucChangedSer {
            get {
                return ResourceManager.GetString("ServiceSucChangedSer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S - Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A - Delete actvity.
        /// </summary>
        internal static string Settings_DelActivity {
            get {
                return ResourceManager.GetString("Settings_DelActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D - Delete current user.
        /// </summary>
        internal static string Settings_DelCurUser {
            get {
                return ResourceManager.GetString("Settings_DelCurUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E - Delete exercise.
        /// </summary>
        internal static string Settings_DelExercise {
            get {
                return ResourceManager.GetString("Settings_DelExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F - Delete food intake.
        /// </summary>
        internal static string Settings_DelFoodIntake {
            get {
                return ResourceManager.GetString("Settings_DelFoodIntake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M - Delete meal.
        /// </summary>
        internal static string Settings_DelMeal {
            get {
                return ResourceManager.GetString("Settings_DelMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R - Return to the main menu.
        /// </summary>
        internal static string Settings_ReturnMainMenu {
            get {
                return ResourceManager.GetString("Settings_ReturnMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S - Switch data service.
        /// </summary>
        internal static string Settings_SwitchDataService {
            get {
                return ResourceManager.GetString("Settings_SwitchDataService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start time of the exercise.
        /// </summary>
        internal static string startExTime {
            get {
                return ResourceManager.GetString("startExTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully deleted.
        /// </summary>
        internal static string SucsDel {
            get {
                return ResourceManager.GetString("SucsDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for staying with us.
        /// </summary>
        internal static string ThankForStaying {
            get {
                return ResourceManager.GetString("ThankForStaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total kilocalories for the current food intake: .
        /// </summary>
        internal static string TotalKcalCurFoodIntake {
            get {
                return ResourceManager.GetString("TotalKcalCurFoodIntake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total kilocalories per food intake: .
        /// </summary>
        internal static string TotalKcalFoodIntake {
            get {
                return ResourceManager.GetString("TotalKcalFoodIntake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X - List of all your exercises.
        /// </summary>
        internal static string UserExercises {
            get {
                return ResourceManager.GetString("UserExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I - List of all your food intakes.
        /// </summary>
        internal static string UserFoodIntakes {
            get {
                return ResourceManager.GetString("UserFoodIntakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U - User profile.
        /// </summary>
        internal static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weight.
        /// </summary>
        internal static string weight {
            get {
                return ResourceManager.GetString("weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.o..
        /// </summary>
        internal static string yo {
            get {
                return ResourceManager.GetString("yo", resourceCulture);
            }
        }
    }
}
