//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFitness.View.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyFitness.View.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E - Add exercise.
        /// </summary>
        internal static string AddExercise {
            get {
                return ResourceManager.GetString("AddExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F - Add food intake.
        /// </summary>
        internal static string AddFoodIntake {
            get {
                return ResourceManager.GetString("AddFoodIntake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A - List of all existing activities.
        /// </summary>
        internal static string AllActivities {
            get {
                return ResourceManager.GetString("AllActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M - List of all existing meals.
        /// </summary>
        internal static string AllMeals {
            get {
                return ResourceManager.GetString("AllMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyFitness was started!.
        /// </summary>
        internal static string AppStarted {
            get {
                return ResourceManager.GetString("AppStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user: .
        /// </summary>
        internal static string CurrentUser {
            get {
                return ResourceManager.GetString("CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D - Delete current user.
        /// </summary>
        internal static string DelCurUser {
            get {
                return ResourceManager.GetString("DelCurUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter date of birth: .
        /// </summary>
        internal static string EnterDateOfBirth {
            get {
                return ResourceManager.GetString("EnterDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter gender: .
        /// </summary>
        internal static string EnterGender {
            get {
                return ResourceManager.GetString("EnterGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter height: .
        /// </summary>
        internal static string EnterHeight {
            get {
                return ResourceManager.GetString("EnterHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username: .
        /// </summary>
        internal static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter weight: .
        /// </summary>
        internal static string EnterWeight {
            get {
                return ResourceManager.GetString("EnterWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q - Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an action:.
        /// </summary>
        internal static string SelectAction {
            get {
                return ResourceManager.GetString("SelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X - List of all your exercises.
        /// </summary>
        internal static string UserExercises {
            get {
                return ResourceManager.GetString("UserExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I - List of all your food intakes.
        /// </summary>
        internal static string UserFoodIntakes {
            get {
                return ResourceManager.GetString("UserFoodIntakes", resourceCulture);
            }
        }
    }
}
